# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "a7a3b9c10e8a5fe0da05ebb65db3ed1d164e612d";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "a7a3b9c10e8a5fe0da05ebb65db3ed1d164e612d";
      fetchSubmodules = false;
      sha256 = "sha256-Aesf0i3fFDvzB/J+serrn+kf9zK7m5spEXg8xn3AbFI=";
    };
    date = "2024-08-03";
  };
  tree-sitter = {
    pname = "tree-sitter";
    version = "779566f588f0cd9a13e4c78b805e82717c98eff3";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter";
      rev = "779566f588f0cd9a13e4c78b805e82717c98eff3";
      fetchSubmodules = false;
      sha256 = "sha256-J84RD+boiEmzcX1L6XR2YwTvQ+P5Fd8rG77I6et9Pgo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./tree-sitter-779566f588f0cd9a13e4c78b805e82717c98eff3/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2024-07-31";
  };
}
