[tree-sitter-ada]

[tree-sitter-agda]

[tree-sitter-angular]

[tree-sitter-apex]
location = "apex"

[tree-sitter-arduino]

[tree-sitter-asm]

[tree-sitter-astro]

[tree-sitter-authzed]

[tree-sitter-awk]

[tree-sitter-bash]

[tree-sitter-bass]

[tree-sitter-beancount]

[tree-sitter-bibtex]

[tree-sitter-bicep]

[tree-sitter-bitbake]

[tree-sitter-blueprint]

[tree-sitter-bp]

[tree-sitter-c]

[tree-sitter-c_sharp]

[tree-sitter-cairo]

[tree-sitter-capnp]

[tree-sitter-chatito]

[tree-sitter-clojure]

[tree-sitter-cmake]

[tree-sitter-comment]

[tree-sitter-commonlisp]

[tree-sitter-cooklang]

[tree-sitter-corn]

[tree-sitter-cpon]

[tree-sitter-cpp]

[tree-sitter-css]

[tree-sitter-csv]
location = "csv"

[tree-sitter-cuda]

[tree-sitter-cue]

[tree-sitter-d]

[tree-sitter-dart]

[tree-sitter-devicetree]

[tree-sitter-dhall]

[tree-sitter-diff]

[tree-sitter-disassembly]

[tree-sitter-djot]

[tree-sitter-dockerfile]

[tree-sitter-dot]

[tree-sitter-doxygen]

[tree-sitter-dtd]
location = "dtd"

[tree-sitter-earthfile]

[tree-sitter-ebnf]
location = "crates/tree-sitter-ebnf"

[tree-sitter-eds]

[tree-sitter-eex]

[tree-sitter-elixir]

[tree-sitter-elm]

[tree-sitter-elsa]

[tree-sitter-elvish]

[tree-sitter-embedded_template]

[tree-sitter-erlang]

[tree-sitter-facility]

[tree-sitter-faust]

[tree-sitter-fennel]

[tree-sitter-fidl]

[tree-sitter-firrtl]

[tree-sitter-fish]

[tree-sitter-foam]

[tree-sitter-forth]

[tree-sitter-fortran]

[tree-sitter-fsh]

[tree-sitter-func]

[tree-sitter-fusion]

[tree-sitter-gdscript]

[tree-sitter-gdshader]

[tree-sitter-git_config]

[tree-sitter-git_rebase]

[tree-sitter-gitattributes]

[tree-sitter-gitcommit]

[tree-sitter-gitignore]

[tree-sitter-gleam]

[tree-sitter-glimmer]

[tree-sitter-glsl]

[tree-sitter-gn]

[tree-sitter-gnuplot]

[tree-sitter-go]

[tree-sitter-godot_resource]

[tree-sitter-gomod]

[tree-sitter-gosum]

[tree-sitter-gotmpl]

[tree-sitter-gowork]

[tree-sitter-gpg]

[tree-sitter-graphql]

[tree-sitter-groovy]

[tree-sitter-gstlaunch]

[tree-sitter-hack]

[tree-sitter-hare]

[tree-sitter-haskell]

[tree-sitter-haskell_persistent]

[tree-sitter-hcl]

[tree-sitter-heex]

[tree-sitter-helm]
location = "dialects/helm"

[tree-sitter-hjson]

[tree-sitter-hlsl]

[tree-sitter-hlsplaylist]

[tree-sitter-hocon]

[tree-sitter-hoon]

[tree-sitter-html]

[tree-sitter-htmldjango]

[tree-sitter-http]

[tree-sitter-hurl]

[tree-sitter-hyprlang]

[tree-sitter-idl]

[tree-sitter-ini]

[tree-sitter-inko]

[tree-sitter-ispc]

[tree-sitter-janet_simple]

[tree-sitter-java]

[tree-sitter-javascript]

[tree-sitter-jq]

[tree-sitter-jsdoc]

[tree-sitter-json]

[tree-sitter-json5]

[tree-sitter-jsonc]

[tree-sitter-jsonnet]

[tree-sitter-julia]

[tree-sitter-just]

[tree-sitter-kconfig]

[tree-sitter-kdl]

[tree-sitter-kotlin]

[tree-sitter-koto]

[tree-sitter-kusto]

[tree-sitter-lalrpop]

[tree-sitter-latex]
generate = true

[tree-sitter-ledger]

[tree-sitter-leo]

[tree-sitter-linkerscript]

[tree-sitter-liquid]

[tree-sitter-liquidsoap]

[tree-sitter-llvm]

[tree-sitter-lua]

[tree-sitter-luadoc]

[tree-sitter-luap]

[tree-sitter-luau]

[tree-sitter-m68k]

[tree-sitter-make]

[tree-sitter-markdown]
location = "tree-sitter-markdown"

[tree-sitter-markdown_inline]
location = "tree-sitter-markdown-inline"

[tree-sitter-matlab]

[tree-sitter-menhir]

[tree-sitter-mermaid]

[tree-sitter-meson]

[tree-sitter-mlir]
generate = true

[tree-sitter-muttrc]

[tree-sitter-nasm]

[tree-sitter-nickel]

[tree-sitter-nim]

[tree-sitter-nim_format_string]

[tree-sitter-ninja]

[tree-sitter-nix]

[tree-sitter-norg]

[tree-sitter-nqc]

[tree-sitter-objc]

[tree-sitter-objdump]

[tree-sitter-ocaml]
location = "grammars/ocaml"

[tree-sitter-ocaml_interface]
location = "grammars/interface"

[tree-sitter-ocamllex]
generate = true

[tree-sitter-odin]

[tree-sitter-org]

[tree-sitter-pascal]

[tree-sitter-passwd]

[tree-sitter-pem]

[tree-sitter-perl]

[tree-sitter-php]
location = "php"

[tree-sitter-php_only]
location = "php_only"

[tree-sitter-phpdoc]

[tree-sitter-pioasm]

[tree-sitter-po]

[tree-sitter-pod]

[tree-sitter-poe_filter]

[tree-sitter-pony]

[tree-sitter-printf]

[tree-sitter-prisma]

[tree-sitter-promql]

[tree-sitter-properties]

[tree-sitter-proto]

[tree-sitter-prql]

[tree-sitter-psv]
location = "psv"

[tree-sitter-pug]

[tree-sitter-puppet]

[tree-sitter-purescript]

[tree-sitter-pymanifest]

[tree-sitter-python]

[tree-sitter-ql]

[tree-sitter-qmldir]

[tree-sitter-qmljs]

[tree-sitter-query]

[tree-sitter-r]

[tree-sitter-racket]

[tree-sitter-ralph]

[tree-sitter-rasi]

[tree-sitter-rbs]

[tree-sitter-re2c]

[tree-sitter-readline]

[tree-sitter-regex]

[tree-sitter-rego]

[tree-sitter-requirements]

[tree-sitter-rnoweb]

[tree-sitter-robot]

[tree-sitter-roc]

[tree-sitter-ron]

[tree-sitter-rst]

[tree-sitter-ruby]

[tree-sitter-rust]

[tree-sitter-scala]

[tree-sitter-scfg]
generate = true

[tree-sitter-scheme]

[tree-sitter-scss]

[tree-sitter-slang]

[tree-sitter-slint]

[tree-sitter-smali]

[tree-sitter-smithy]

[tree-sitter-snakemake]

[tree-sitter-solidity]

[tree-sitter-soql]
location = "soql"

[tree-sitter-sosl]
location = "sosl"

[tree-sitter-sourcepawn]

[tree-sitter-sparql]

[tree-sitter-sql]

[tree-sitter-squirrel]

[tree-sitter-ssh_config]

[tree-sitter-starlark]

[tree-sitter-strace]

[tree-sitter-styled]

[tree-sitter-supercollider]

[tree-sitter-surface]

[tree-sitter-svelte]

[tree-sitter-swift]
generate = true

[tree-sitter-sxhkdrc]

[tree-sitter-systemtap]

[tree-sitter-t32]

[tree-sitter-tablegen]

[tree-sitter-tact]

[tree-sitter-tcl]

[tree-sitter-teal]
generate = true

[tree-sitter-templ]

[tree-sitter-terraform]
location = "dialects/terraform"

[tree-sitter-textproto]

[tree-sitter-thrift]

[tree-sitter-tiger]

[tree-sitter-tlaplus]

[tree-sitter-tmux]

[tree-sitter-todotxt]

[tree-sitter-toml]

[tree-sitter-tsv]
location = "tsv"

[tree-sitter-tsx]
location = "tsx"

[tree-sitter-turtle]

[tree-sitter-twig]

[tree-sitter-typescript]
location = "typescript"

[tree-sitter-typespec]

[tree-sitter-typoscript]

[tree-sitter-typst]

[tree-sitter-udev]

[tree-sitter-ungrammar]

[tree-sitter-unison]
generate = true

[tree-sitter-usd]

[tree-sitter-uxntal]

[tree-sitter-v]
location = "tree_sitter_v"

[tree-sitter-vala]

[tree-sitter-vento]

[tree-sitter-verilog]

[tree-sitter-vhs]

[tree-sitter-vim]

[tree-sitter-vimdoc]

[tree-sitter-vue]

[tree-sitter-wgsl]

[tree-sitter-wgsl_bevy]

[tree-sitter-wing]

[tree-sitter-wit]

[tree-sitter-xcompose]

[tree-sitter-xml]
location = "xml"

[tree-sitter-yaml]

[tree-sitter-yang]

[tree-sitter-yuck]

[tree-sitter-zathurarc]

[tree-sitter-zig]

