[package]
name = "ts-pg"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.155"
nix = { version = "0.29.0", default-features = false }
once_cell = "1.19.0"
tree-sitter = "0.22.6"
tree-sitter-highlight = "0.22.6"
tree-sitter-rust = "0.21.2"

[build-dependencies]
cc = "1.1.5"
