[package]
name = "tree-sitter-cat"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
itertools = "0.13.0"
tree-sitter-dynamic = { version = "0.1.0", path = "../tree-sitter-dynamic" }
tree-sitter-highlight = "0.22.6"
