prefix = "\u001B"
end = "\u001B[0m"

[theme]

"comment" = "[90;3m"
"comment.documentation" = "[90;3m"

"type" = "[33m"
"type.builtin" = "[33;3m"

"attribute" = "[93m"
"constant.builtin" = "[91m"
"constant" = "[93m"
"constructor" = "[94m"
"function.builtin" = "[94m"
"function.macro" = "[94m"
"function" = "[34m"
"keyword" = "[95m"
"module" = "[31m"
"number" = "[91m"
"operator" = "[95m"
"punctuation.bracket" = "[90m"
"punctuation.delimiter" = "[90m"
"string.special" = "[92m"
"string" = "[32m"
"tag" = "[33m"
"variable.builtin" = "[31m"
"variable.member" = "[0m"
"variable" = "[91m"
